[theme]
base="dark"
borderColor="mediumSlateBlue"
showWidgetBorder=false
font = "Nunito:https://fonts.googleapis.com/css2?family=Nunito&display=swap"
codeFont = "'Space Mono':https://fonts.googleapis.com/css2?family=Space+Mono&display=swap"

[theme.sidebar]
showWidgetBorder=true